#' @title Fi_score_plot
#'
#' @description Function to plot Fi-score values per amino acid using a bar plot; NOTE: some PDB files have breakages in their amino acid sequence, that is some residues might be missing and the gaps will be reflected in the plot
#'
#' @param pdb_df Requires a PDB data frame generated by PDB_prepare
#' @return  Bar plot
#' @import ggplot2
#' @export
Fi_score_plot<-function(pdb_df){


ggplot2::ggplot(pdb_df) + ggplot2::geom_bar(ggplot2::aes(x=df_resno, y = Fi_score), color="grey", alpha=0.2, stat = "identity")+ggplot2::scale_x_continuous(expand = c(0,0))+ggplot2::ggtitle(label="Fi-score  value distribution")+ggplot2::xlab(label="Residue number")+ggplot2::ylab(label="Fi-score")





}
