#' @title Fiscore_secondary
#'
#' @description Function plots a bar plot with  a secondary structure element visualisation based on PDB file data; NOTE: NA refers to unidentified region, e.g., a  likely disordered or unstructured region
#'
#' @param pdb_df Requires a PDB data frame generated by PDB_prepare
#' @return bar plot
#' @import ggplot2
#' @import plotly
#' @export
Fiscore_secondary<-function(pdb_df){


ggplot2::ggplot(pdb_df) + ggplot2::geom_bar(ggplot2::aes(x=df_resno, y = Fi_score, fill=Type),  stat = "identity")+ggplot2::scale_x_continuous(expand = c(0,0))+ggplot2::ggtitle(label="Fi-score  value distribution for secondary structures")+ggplot2::xlab(label="Residue number")+ggplot2::ylab(label="Fi-score")





}
