#' @title phi_psi_plot
#'
#' @description Function to plot a PDB file phi/psi angle density plot
#'
#' @param pdb_df Requires a PDB data frame generated by PDB_prepare
#' @return  2D phi/psi angle distribution plot with residues binned
#' @import ggplot2
#' @importFrom ggplot2 aes
#' @export
phi_psi_plot<-function(pdb_df){


  ggplot2::ggplot(data=pdb_df)+ggplot2::geom_hex(ggplot2::aes(x=phi, y =psi))+ggplot2::scale_x_continuous(breaks=c(-180,-120,-60,0,60,120,180),limits = c(-180, 180), expand = c(0,0)) +ggplot2::scale_y_continuous(breaks=c(-180,-120,-60,0,60,120,180),limits = c(-180,180), expand = c(0,0))+ggplot2::labs(x="phi",y="psi")+ ggplot2::theme_bw()






}
