#' @title phi_psi_bar_plot
#'
#' @description Function to plot PDB file dihedral angle distribution per amino acid using a bar plot. NOTE: some PDB files have breakages in their amino acid sequences; that is, some residues might be missing and it will be reflected in the plot via empty spaces
#'
#' @param pdb_df Requires a PDB data frame generated by PDB_prepare
#' @return  Bar plot
#' @import ggplot2
#' @import plotly
#' @export
phi_psi_bar_plot<-function(pdb_df){



  #Plot will capture breakage regions with empty
  plot_bar<-ggplot2::ggplot(pdb_df) + ggplot2::geom_bar(ggplot2::aes(x=df_resno, y = phi), color="red", alpha=0.2, stat = "identity")+ggplot2::geom_bar(aes(x =df_resno, y = psi), color="blue", alpha=0.2, stat = "identity") +ggplot2::labs(x="Residue number",y="phi/psi")+ggplot2::scale_x_continuous(breaks=seq(0,nrow(pdb_df),25), expand = c(0,0))+ggplot2::scale_y_continuous(breaks=c(-180,-120,-60,0,60,120,180),limits = c(-180,180), expand = c(0,0))+ggplot2::ggtitle(label="Dihedral angle distribution, psi - blue and phi - red ")


  plotly::ggplotly(plot_bar)


}
