#' @title phi_psi_interactive
#'
#' @description Function plots a scatter plot with  a secondary structure element visualisation based on the PDB file data; NOTE: NA refers to unidentified region, e.g., a disordered region
#'
#' @param pdb_df Requires a PDB data frame generated by PDB_prepare
#' @return Interactive plot
#' @import ggplot2
#' @import plotly
#' @export
phi_psi_interactive<-function(pdb_df){


  plot_angles<-ggplot2::ggplot(data=pdb_df)+ggplot2::geom_point(ggplot2::aes(x=phi, y = psi, color=Type))+ggplot2::scale_x_continuous(breaks=c(-180,-120,-60,0,60,120,180),limits = c(-180, 180), expand = c(0,0)) +ggplot2::scale_y_continuous(breaks=c(-180,-120,-60,0,60,120,180),limits = c(-180,180), expand = c(0,0))+ggplot2::labs(x="phi",y="psi")

  plotly::ggplotly(plot_angles)



}
